export const countries: string[] = [
    'United States',
    'China',
    'India',
    'Indonesia',
    'Pakistan',
    'Brazil',
    'Nigeria',
    'Bangladesh',
    'Russia',
    'Mexico',
    'Japan',
    'Ethiopia',
    'Philippines',
    'Egypt',
    'Vietnam',
    'DR Congo',
    'Turkey',
    'Iran',
    'Germany',
    'Thailand',
    'United Kingdom',
    'France',
    'Italy',
    'Tanzania',
    'South Africa',
    'Myanmar',
    'Kenya',
    'South Korea',
    'Colombia',
    'Spain',
    'Uganda',
    'Argentina',
    'Algeria',
    'Sudan',
    'Ukraine',
    'Iraq',
    'Afghanistan',
    'Poland',
    'Canada',
    'Morocco',
    'Saudi Arabia',
    'Uzbekistan',
    'Peru',
    'Angola',
    'Malaysia',
    'Mozambique',
    'Ghana',
    'Yemen',
    'Nepal',
    'Venezuela',
    'Madagascar'
];
