apiVersion: v1
kind: Service
metadata:
  name: fair-energy-ai-frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: webui
      targetPort: 3000
      protocol: TCP
  selector:
    app: fair-energy-ai-frontend
